In [1]:
#! pip install translators
#! pip install contractions
#! pip install textblob
#! pip install Pattern

#nltk.download('omw-1.4')

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')
#2 construction
from contractions import contractions_dict

#3 translate
import re
import langdetect
import translators as ts

#4 values analysis
import plotly.express as px

#5 sentiment analysis
from nltk.sentiment.vader import SentimentIntensityAnalyzer

#6 stopwords

import nltk
nltk.download('stopwords') 
from nltk.corpus import stopwords
stopwords_eng = stopwords.words('english')  

#7 WordCloud
from textblob import TextBlob
from pattern.en import pluralize, singularize
from collections import Counter
from wordcloud import WordCloud 
import matplotlib.pyplot as plt

#8 lemmatization
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.tokenize import word_tokenize

#9 model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

#train
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#nltk.downloader.download('vader_lexicon')
#nltk.download('omw-1.4')
#nltk.download('brown')

Using state Hesse server backend.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sagrawa4\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
def expand_contractions(text, contraction_mapping=contractions_dict):
    
    contractions_pattern = re.compile('({})'.format('|'.join(contraction_mapping.keys())), 
                                      flags=re.IGNORECASE|re.DOTALL)
    def expand_match(contraction):
        match = contraction.group(0)
        first_char = match[0]
        expanded_contraction = contraction_mapping.get(match)\
                                if contraction_mapping.get(match)\
                                else contraction_mapping.get(match.lower())  
        while not AttributeError:
            try:
                expanded_contraction = first_char+expanded_contraction[1:]
            except:
                continue
            return expanded_contraction
        
    expanded_text = contractions_pattern.sub(expand_match, text)
    expanded_text = re.sub("'", "", expanded_text)
    return expanded_text

In [4]:
tweets = pd.read_excel(r'C:\Users\sagrawa4\Desktop\Cryptomatter-project\Data/bitcoin_tweets_2017_2022.xlsx', index_col=[0])
tweets.Date = pd.to_datetime(tweets.Date)
tweets['Date'] = tweets.Date.dt.date

In [5]:
tweets

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin… Fast forward 13 years...,37,49,511
1,Healthy Pockets,@healthy_pockets,2022-11-26,Qué crees que veremos antes en #Bitcoin ? \n\n...,177,29,673
2,Jason A. Williams,@GoingParabolic,2022-11-26,#Bitcoin is dead.\n224\n37\n567,224,37,567
3,sunnydecree,@sunnydecree,2022-11-26,It's Bitcoin. Just Bitcoin.\n\nNot Blockchain ...,121,42,520
4,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527
...,...,...,...,...,...,...,...
47863,Charlie,@MoistCr1TiKaL,2017-01-14,#WhatIWouldITellA15YearOldMe invest everything...,14,261,1 576
47864,CaptainSparklez,@CaptainSparklez,2017-01-14,#WhatIWouldTellA15YearOldMe\nHere are the winn...,32,249,2 524
47865,Bitcoin News,@BTCTN,2017-01-11,Did Julian Assange Just Use the Bitcoin Blockc...,30,563,1 028
47866,WikiLeaks,@wikileaks,2017-01-11,Julian Assange Just Read Out a \n@Bitcoin\n Bl...,116,906,1 323
47867,Kim Dotcom,@KimDotcom,2017-01-01,#Bitcoin hits $1000\nAnd it's just the beginni...,47,391,842

# Translate all to English

In [6]:
import re
import langdetect
import translators as ts

In [7]:
for i in range(0, len(tweets)):
    tweets['Text'][i] = expand_contractions(tweets['Text'][i])
    
    tweets['Text'][i] = re.sub("[^A-Za-z]", " ", tweets['Text'][i])
    tweets['Text'][i] = re.sub(" +", " ",tweets['Text'][i])
    
    
    if len(tweets.loc[i, 'Text']) > 1:
        tweets.loc[i, 'lang'] = langdetect.detect(tweets.loc[i, 'Text'])

In [8]:
tweets_ = tweets

In [9]:
import translators as ts
import translators.server as tss
import warnings
warnings.filterwarnings('ignore')

tweets_ = tweets_[tweets_['lang'].notnull()]
tweets_ = tweets_.loc[tweets_['lang'] != '']
tweets_.reset_index(drop=True, inplace= True)
len(tweets_)

tweets_en = tweets_[tweets_['lang']=='en']
tweets_non_en = tweets_[tweets_['lang']!='en']
tweets_en.reset_index(drop=True, inplace= True)
tweets_non_en.reset_index(drop=True, inplace= True)

tweets_non_en['en'] = ''
tweets_non_en['en'][0] = tss.google(tweets_non_en['Text'][0], from_language=tweets_non_en['lang'][0], to_language='en')

In [10]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en
...,...,...,...,...,...,...,...,...
44377,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en
44378,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en
44379,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en
44380,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en
44381,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en

# Tonality Analysis

In [11]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en
...,...,...,...,...,...,...,...,...
44377,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en
44378,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en
44379,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en
44380,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en
44381,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en

In [12]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
import warnings
warnings.filterwarnings('ignore')

tweets_en['Text'] = tweets_en['Text'].astype(str)

sentiments = SentimentIntensityAnalyzer()
tweets_en["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in tweets_en["Text"]]
tweets_en["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in tweets_en["Text"]]
tweets_en["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in tweets_en["Text"]]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\sagrawa4\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [13]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang,Positive,Negative,Neutral
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en,0.076,0.128,0.797
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en,0.000,0.683,0.317
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en,0.000,0.000,1.000
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en,0.000,0.212,0.788
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en,0.302,0.000,0.698
...,...,...,...,...,...,...,...,...,...,...,...
44377,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en,0.000,0.000,1.000
44378,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en,0.395,0.000,0.605
44379,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en,0.129,0.000,0.871
44380,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en,0.087,0.193,0.720
44381,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en,0.000,0.000,1.000

In [14]:
tweets_en.loc[tweets_en['Handle'] == '@elonmusk']

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang,Positive,Negative,Neutral
10570,Elon Musk,@elonmusk,2022-03-14,elonmusk saylor As a general principle for th...,4 056,"15,9 тыс.","58,3 тыс.",en,0.159,0.000,0.841
18002,Elon Musk,@elonmusk,2021-11-20,WSBChairman Bitcoin cures cancer,4 833,6 604,"40,3 тыс.",en,0.000,0.595,0.405
19564,Elon Musk,@elonmusk,2021-10-24,Filasophical ShibaInuHodler Out of curiosity ...,5 229,7 229,"34,9 тыс.",en,0.120,0.000,0.880
19565,Elon Musk,@elonmusk,2021-10-24,itsALLrisky TeslaGong Possibly Bitcoin was co...,725,864,5 225,en,0.123,0.124,0.752
24285,Elon Musk,@elonmusk,2021-07-28,heydave We have that many Bitcoin but close,3 213,1 413,"24,7 тыс.",en,0.000,0.000,1.000
25907,Elon Musk,@elonmusk,2021-06-25,not funny Bitcoin maxis,3 372,2 985,"57,2 тыс.",en,0.000,0.445,0.555
26614,Elon Musk,@elonmusk,2021-06-13,Cointelegraph This is inaccurate Tesla only s...,9 214,"12,7 тыс.","51,6 тыс.",en,0.241,0.000,0.759
27533,Elon Musk,@elonmusk,2021-06-05,lexfridman VitalikButerin I pretty much agree...,1 892,3 767,"23,3 тыс.",en,0.533,0.000,0.467
28395,Elon Musk,@elonmusk,2021-05-20,TeslaGong wintonARK Bitcoin hashing aka minin...,1 458,1 063,5 358,en,0.159,0.000,0.841
31490,Elon Musk,@elonmusk,2021-03-24,Pay by Bitcoin capability available outside US...,2 943,9 003,"132,1 тыс.",en,0.000,0.135,0.865
31491,Elon Musk,@elonmusk,2021-03-24,Tesla is using only internal open source softw...,4 432,22 тыс.,"168,1 тыс.",en,0.042,0.000,0.958
31494,Elon Musk,@elonmusk,2021-03-24,You can now buy a Tesla with Bitcoin,"33,8 тыс.","127,7 тыс.","839,2 тыс.",en,0.000,0.000,1.000
32078,Elon Musk,@elonmusk,2021-03-12,BTC Bitcoin is an anagram of TBC The Boring Co...,11 тыс.,"18,2 тыс.","227,9 тыс.",en,0.000,0.173,0.827
33205,Elon Musk,@elonmusk,2021-02-19,elonmusk business To be clear I am not an inv...,1 978,6 944,"32,7 тыс.",en,0.105,0.124,0.771
33207,Elon Musk,@elonmusk,2021-02-19,business Tesla s action is not directly refle...,897,3 501,"25,7 тыс.",en,0.074,0.093,0.833
36073,Elon Musk,@elonmusk,2020-12-20,Bitcoin is almost as bs as fiat money,7 624,"12,7 тыс.","129,3 тыс.",en,0.000,0.000,1.000
36081,Elon Musk,@elonmusk,2020-12-20,Bitcoin is my safe word,6 257,"21,4 тыс.","222,1 тыс.",en,0.420,0.000,0.580
39038,Elon Musk,@elonmusk,2020-05-15,jk rowling Pretty much although massive curre...,688,3 203,"14,1 тыс.",en,0.271,0.000,0.729
39265,Elon Musk,@elonmusk,2020-05-01,Bitcoin How much for some anime Bitcoin,727,2 517,"17,1 тыс.",en,0.000,0.000,1.000
39266,Elon Musk,@elonmusk,2020-05-01,Bitcoin,152,182,4 785,en,0.000,0.000,1.000
40005,Elon Musk,@elonmusk,2020-01-10,Bitcoin is not my safe word,2 579,8 979,"111,7 тыс.",en,0.000,0.325,0.675

### Reading BTC Data

In [15]:
btc_data = pd.read_csv(r'C:\Users\sagrawa4\Desktop\Cryptomatter-project\Data\BTC_data.csv', delimiter=";")
btc_data['Date'] = pd.to_datetime(btc_data['Date'], infer_datetime_format=True, utc=True, errors='ignore')
btc_data['Date'] = btc_data.Date.dt.date
btc_data

            Date    MarketCap  TradeVolume  ClosePrice
0     2013-12-31   9358690000     23448600      767.74
1     2014-01-02   9417080000     16837800      772.53
2     2014-01-03  10062400000     54171500      825.47
3     2014-01-04  10351000000     36344700      849.14
4     2014-01-05  11207500000     62414600      919.41
...          ...          ...          ...         ...
3121  2022-11-16  3,24608E+11  28676300000    16890.50
3122  2022-11-17  3,20099E+11  26922000000    16689.40
3123  2022-11-18  3,21287E+11  22011300000    16718.40
3124  2022-11-19  3,20877E+11  20942200000    16707.00
3125  2022-11-20  3,21151E+11  10844500000    16712.70

[3126 rows x 4 columns]

### Merging sentiment and BTC data

In [16]:
df_merged = tweets_en.merge(btc_data, on='Date')
#df_merged = df_merged[['Date','Text','Reply_cnt','Retweet_cnt','Like_cnt','Positive','Negative','Neutral','ClosePrice']]
df_merged = df_merged[['Date','Positive','Negative','Neutral','ClosePrice']]
display(df_merged)

             Date  Positive  Negative  Neutral  ClosePrice
0      2022-11-20     0.000     0.000    1.000   16712.700
1      2022-11-20     0.182     0.085    0.733   16712.700
2      2022-11-20     0.000     0.000    1.000   16712.700
3      2022-11-20     0.233     0.183    0.583   16712.700
4      2022-11-20     0.118     0.291    0.591   16712.700
...           ...       ...       ...      ...         ...
43428  2017-01-14     0.000     0.000    1.000     817.825
43429  2017-01-14     0.395     0.000    0.605     817.825
43430  2017-01-11     0.129     0.000    0.871     784.278
43431  2017-01-11     0.087     0.193    0.720     784.278
43432  2017-01-01     0.000     0.000    1.000     998.050

[43433 rows x 5 columns]

In [17]:
# #type(df_merged['Date'])
# df_temp=df_merged.head(78)
# df_temp = df_temp["ClosePrice"].mean()
# print(df_temp)

### Using GroupBy('Date') and taking average

In [18]:
df_merged.groupby(['Date']).mean()

            Positive  Negative   Neutral  ClosePrice
Date
2017-01-01  0.000000  0.000000  1.000000     998.050
2017-01-11  0.108000  0.096500  0.795500     784.278
2017-01-14  0.197500  0.000000  0.802500     817.825
2017-02-19  0.095000  0.000000  0.905000    1053.500
2017-03-17  0.425000  0.050000  0.525000    1074.090
...              ...       ...       ...         ...
2022-11-16  0.105100  0.046940  0.847980   16890.500
2022-11-17  0.054128  0.050205  0.895692   16689.400
2022-11-18  0.090607  0.068754  0.840705   16718.400
2022-11-19  0.119124  0.066528  0.814337   16707.000
2022-11-20  0.099974  0.083295  0.816756   16712.700

[1805 rows x 4 columns]

### Reading BTC Binance Data

In [26]:
btc_binance = pd.read_csv(r'C:\Users\sagrawa4\Desktop\Cryptomatter-project\Data\BTC_Binance.csv', delimiter=";")
btc_binance.rename(columns={'UNIX timestamp': 'Date'}, inplace=True)
btc_binance['Date']=btc_binance['Date'].str.replace(',', '.').astype(float)
btc_binance.Date = pd.to_datetime(btc_binance.Date, unit='ms')
btc_binance['Date'] = btc_binance.Date.dt.date

btc_binance

,first_currency,second_currency,Date,open,high,low,close,volume
0,BTC,USDT,2017-08-17,4261.48,4485.39,4200.74,4285.08,795.150
1,BTC,USDT,2017-08-18,4285.08,4371.52,3938.77,4108.37,1199.890
2,BTC,USDT,2017-08-20,4108.37,4184.69,3850.00,4139.98,381.310
3,BTC,USDT,2017-08-20,4120.98,4211.08,4032.62,4086.29,467.083
4,BTC,USDT,2017-08-22,4069.13,4119.62,3911.79,4016.00,691.743
...,...,...,...,...,...,...,...,...
1918,BTC,USDT,2022-11-18,16661.60,16751.00,16410.70,16692.60,228039.000
1919,BTC,USDT,2022-11-19,16692.60,17011.00,16546.00,16700.40,214224.000
1920,BTC,USDT,2022-11-19,16699.40,16822.40,16553.50,16700.70,104963.000
1921,BTC,USDT,2022-11-21,16700.70,16753.30,16180.00,16280.20,154842.000
1922,BTC,USDT,2022-11-22,16279.50,16319.00,15476.00,15781.30,324097.000

In [29]:
df_merged_binance = tweets_en.merge(btc_binance, on='Date')
df_merged_binance = df_merged_binance[['Date','Positive','Negative','Neutral','close']]
display(df_merged_binance)

             Date  Positive  Negative  Neutral     close
0      2022-11-22     0.000     0.000    1.000  15781.30
1      2022-11-22     0.125     0.063    0.812  15781.30
2      2022-11-22     0.000     0.000    1.000  15781.30
3      2022-11-22     0.101     0.198    0.702  15781.30
4      2022-11-22     0.000     0.000    1.000  15781.30
...           ...       ...       ...      ...       ...
44294  2017-08-22     0.055     0.288    0.657   4016.00
44295  2017-08-22     0.441     0.000    0.559   4016.00
44296  2017-08-22     0.000     0.000    1.000   4016.00
44297  2017-08-17     0.000     0.000    1.000   4285.08
44298  2017-08-17     0.000     0.065    0.935   4285.08

[44299 rows x 5 columns]

In [28]:
df_merged_binance.groupby(['Date']).mean()

            Positive  Negative   Neutral      close
Date
2017-08-17  0.000000  0.032500  0.967500   4285.080
2017-08-22  0.165333  0.096000  0.738667   4016.000
2017-08-23  0.115333  0.066000  0.818667   4077.005
2017-08-25  0.000000  0.189500  0.810500   4316.010
2017-08-29  0.083500  0.020250  0.896250   4587.480
...              ...       ...       ...        ...
2022-11-16  0.105100  0.046940  0.847980  16781.700
2022-11-18  0.090607  0.068754  0.840705  16692.600
2022-11-19  0.119124  0.066528  0.814337  16700.550
2022-11-21  0.108903  0.077381  0.813716  16280.200
2022-11-22  0.114786  0.057580  0.827634  15781.300

[1165 rows x 4 columns]

### Modelling

- Use df_merged & df_merged_binance dataframe to do the modelling.