In [1]:
! pip install translators
! pip install contractions
! pip install textblob
! pip install Pattern

#nltk.download('omw-1.4')

Requirement already satisfied: translators in c:\users\lakshi\anaconda3\lib\site-packages (5.5.5)
Requirement already satisfied: lxml>=4.9.1 in c:\users\lakshi\anaconda3\lib\site-packages (from translators) (4.9.2)
Requirement already satisfied: pathos>=0.2.9 in c:\users\lakshi\anaconda3\lib\site-packages (from translators) (0.3.0)
Requirement already satisfied: PyExecJS>=1.5.1 in c:\users\lakshi\anaconda3\lib\site-packages (from translators) (1.5.1)
Requirement already satisfied: cryptography>=38.0.1 in c:\users\lakshi\anaconda3\lib\site-packages (from translators) (39.0.0)
Requirement already satisfied: requests>=2.28.1 in c:\users\lakshi\anaconda3\lib\site-packages (from translators) (2.28.1)
Requirement already satisfied: cffi>=1.12 in c:\users\lakshi\anaconda3\lib\site-packages (from cryptography>=38.0.1->translators) (1.14.5)
Requirement already satisfied: dill>=0.3.6 in c:\users\lakshi\anaconda3\lib\site-packages (from pathos>=0.2.9->translators) (0.3.6)
Requirement already satisfied: ppft>=1.7.6.6 in c:\users\lakshi\anaconda3\lib\site-packages (from pathos>=0.2.9->translators) (1.7.6.6)
Requirement already satisfied: multiprocess>=0.70.14 in c:\users\lakshi\anaconda3\lib\site-packages (from pathos>=0.2.9->translators) (0.70.14)
Requirement already satisfied: pox>=0.3.2 in c:\users\lakshi\anaconda3\lib\site-packages (from pathos>=0.2.9->translators) (0.3.2)
Requirement already satisfied: six>=1.10.0 in c:\users\lakshi\anaconda3\lib\site-packages (from PyExecJS>=1.5.1->translators) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lakshi\anaconda3\lib\site-packages (from requests>=2.28.1->translators) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\lakshi\anaconda3\lib\site-packages (from requests>=2.28.1->translators) (1.26.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\lakshi\anaconda3\lib\site-packages (from requests>=2.28.1->translators) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lakshi\anaconda3\lib\site-packages (from requests>=2.28.1->translators) (2020.12.5)
Requirement already satisfied: pycparser in c:\users\lakshi\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.1->translators) (2.20)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: contractions in c:\users\lakshi\anaconda3\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\lakshi\anaconda3\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\lakshi\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.1)
Requirement already satisfied: pyahocorasick in c:\users\lakshi\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (1.4.4)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: textblob in c:\users\lakshi\anaconda3\lib\site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in c:\users\lakshi\anaconda3\lib\site-packages (from textblob) (3.5)
Requirement already satisfied: click in c:\users\lakshi\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (7.1.2)
Requirement already satisfied: joblib in c:\users\lakshi\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (1.0.1)
Requirement already satisfied: tqdm in c:\users\lakshi\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (4.59.0)
Requirement already satisfied: regex in c:\users\lakshi\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (2021.4.4)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: Pattern in c:\users\lakshi\anaconda3\lib\site-packages (3.6)
Requirement already satisfied: backports.csv in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (1.0.7)
Requirement already satisfied: cherrypy in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (18.8.0)
Requirement already satisfied: python-docx in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (0.8.11)
Requirement already satisfied: scipy in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (1.7.3)
Requirement already satisfied: future in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (0.18.2)
Requirement already satisfied: numpy in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (1.20.1)
Requirement already satisfied: requests in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (2.28.1)
Requirement already satisfied: mysqlclient in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (2.1.1)
Requirement already satisfied: nltk in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (3.5)
Requirement already satisfied: beautifulsoup4 in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (4.9.3)
Requirement already satisfied: lxml in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (4.9.2)
Requirement already satisfied: feedparser in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (6.0.10)
Requirement already satisfied: pdfminer.six in c:\users\lakshi\anaconda3\lib\site-packages (from Pattern) (20221105)
Requirement already satisfied: soupsieve>1.2 in c:\users\lakshi\anaconda3\lib\site-packages (from beautifulsoup4->Pattern) (2.2.1)
Requirement already satisfied: portend>=2.1.1 in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (3.1.0)
Requirement already satisfied: more-itertools in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (8.7.0)
Requirement already satisfied: zc.lockfile in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (2.0)
Requirement already satisfied: cheroot>=8.2.1 in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (9.0.0)
Requirement already satisfied: jaraco.collections in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (3.8.0)
Requirement already satisfied: pywin32>=227 in c:\users\lakshi\anaconda3\lib\site-packages (from cherrypy->Pattern) (227)
Requirement already satisfied: sgmllib3k in c:\users\lakshi\anaconda3\lib\site-packages (from feedparser->Pattern) (1.0.0)
Requirement already satisfied: regex in c:\users\lakshi\anaconda3\lib\site-packages (from nltk->Pattern) (2021.4.4)
Requirement already satisfied: tqdm in c:\users\lakshi\anaconda3\lib\site-packages (from nltk->Pattern) (4.59.0)
Requirement already satisfied: joblib in c:\users\lakshi\anaconda3\lib\site-packages (from nltk->Pattern) (1.0.1)
Requirement already satisfied: click in c:\users\lakshi\anaconda3\lib\site-packages (from nltk->Pattern) (7.1.2)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\lakshi\anaconda3\lib\site-packages (from pdfminer.six->Pattern) (39.0.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\lakshi\anaconda3\lib\site-packages (from pdfminer.six->Pattern) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lakshi\anaconda3\lib\site-packages (from requests->Pattern) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\lakshi\anaconda3\lib\site-packages (from requests->Pattern) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lakshi\anaconda3\lib\site-packages (from requests->Pattern) (2020.12.5)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: jaraco.functools in c:\users\lakshi\anaconda3\lib\site-packages (from cheroot>=8.2.1->cherrypy->Pattern) (3.5.2)
Requirement already satisfied: six>=1.11.0 in c:\users\lakshi\anaconda3\lib\site-packages (from cheroot>=8.2.1->cherrypy->Pattern) (1.15.0)
Requirement already satisfied: cffi>=1.12 in c:\users\lakshi\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six->Pattern) (1.14.5)
Requirement already satisfied: tempora>=1.8 in c:\users\lakshi\anaconda3\lib\site-packages (from portend>=2.1.1->cherrypy->Pattern) (5.2.0)
Requirement already satisfied: jaraco.classes in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.collections->cherrypy->Pattern) (3.2.3)
Requirement already satisfied: jaraco.text in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.collections->cherrypy->Pattern) (3.11.0)
Requirement already satisfied: setuptools in c:\users\lakshi\anaconda3\lib\site-packages (from zc.lockfile->cherrypy->Pattern) (65.3.0)
Requirement already satisfied: pycparser in c:\users\lakshi\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six->Pattern) (2.20)
Requirement already satisfied: pytz in c:\users\lakshi\anaconda3\lib\site-packages (from tempora>=1.8->portend>=2.1.1->cherrypy->Pattern) (2021.1)
Requirement already satisfied: inflect in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.text->jaraco.collections->cherrypy->Pattern) (6.0.2)
Requirement already satisfied: jaraco.context>=4.1 in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.text->jaraco.collections->cherrypy->Pattern) (4.2.0)
Requirement already satisfied: importlib-resources in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.text->jaraco.collections->cherrypy->Pattern) (5.10.2)
Requirement already satisfied: autocommand in c:\users\lakshi\anaconda3\lib\site-packages (from jaraco.text->jaraco.collections->cherrypy->Pattern) (2.2.2)
Requirement already satisfied: zipp>=3.1.0 in c:\users\lakshi\anaconda3\lib\site-packages (from importlib-resources->jaraco.text->jaraco.collections->cherrypy->Pattern) (3.4.1)
Requirement already satisfied: pydantic>=1.9.1 in c:\users\lakshi\anaconda3\lib\site-packages (from inflect->jaraco.text->jaraco.collections->cherrypy->Pattern) (1.9.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\lakshi\anaconda3\lib\site-packages (from pydantic>=1.9.1->inflect->jaraco.text->jaraco.collections->cherrypy->Pattern) (4.4.0)

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.optimizers import Adam, Adadelta
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [46]:
from seglearn.transform import FeatureRep, SegmentXYForecast, last
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

In [48]:
from sklearn import metrics

In [49]:
!pip install --upgrade xlrd

Requirement already satisfied: xlrd in c:\users\lakshi\anaconda3\lib\site-packages (2.0.1)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')
#2 construction
from contractions import contractions_dict

#3 translate
import re
import langdetect
import translators as ts

#4 values analysis
import plotly.express as px

#5 sentiment analysis
from nltk.sentiment.vader import SentimentIntensityAnalyzer

#6 stopwords

import nltk
nltk.download('stopwords') 
from nltk.corpus import stopwords
stopwords_eng = stopwords.words('english')  

#7 WordCloud
from textblob import TextBlob
from pattern.en import pluralize, singularize
from collections import Counter
from wordcloud import WordCloud 
import matplotlib.pyplot as plt

#8 lemmatization
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.tokenize import word_tokenize

#9 model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

#train
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#nltk.downloader.download('vader_lexicon')
#nltk.download('omw-1.4')
#nltk.download('brown')

Using state Bavaria server backend.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
def expand_contractions(text, contraction_mapping=contractions_dict):
    
    contractions_pattern = re.compile('({})'.format('|'.join(contraction_mapping.keys())), 
                                      flags=re.IGNORECASE|re.DOTALL)
    def expand_match(contraction):
        match = contraction.group(0)
        first_char = match[0]
        expanded_contraction = contraction_mapping.get(match)\
                                if contraction_mapping.get(match)\
                                else contraction_mapping.get(match.lower())  
        while not AttributeError:
            try:
                expanded_contraction = first_char+expanded_contraction[1:]
            except:
                continue
            return expanded_contraction
        
    expanded_text = contractions_pattern.sub(expand_match, text)
    expanded_text = re.sub("'", "", expanded_text)
    return expanded_text

In [9]:
tweets = pd.read_excel(r'C:\Users\Lakshi\Downloads\Cryptomatter-project-data-preprocessing\Cryptomatter-project-data-preprocessing\Data\bitcoin_tweets_2017_2022.xlsx', index_col=[0])
tweets.Date = pd.to_datetime(tweets.Date)

In [10]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
import warnings
warnings.filterwarnings('ignore')

tweets_en2['Text'] = tweets_en2['Text'].astype(str)

sentiments = SentimentIntensityAnalyzer()
tweets_en2["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in tweets_en2["Text"]]
tweets_en2["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in tweets_en2["Text"]]
tweets_en2["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in tweets_en2["Text"]]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Lakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [11]:
tweets['Date'] = tweets.Date.dt.date

In [12]:
tweets

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin… Fast forward 13 years...,37,49,511
1,Healthy Pockets,@healthy_pockets,2022-11-26,Qué crees que veremos antes en #Bitcoin ? \n\n...,177,29,673
2,Jason A. Williams,@GoingParabolic,2022-11-26,#Bitcoin is dead.\n224\n37\n567,224,37,567
3,sunnydecree,@sunnydecree,2022-11-26,It's Bitcoin. Just Bitcoin.\n\nNot Blockchain ...,121,42,520
4,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527
...,...,...,...,...,...,...,...
47863,Charlie,@MoistCr1TiKaL,2017-01-14,#WhatIWouldITellA15YearOldMe invest everything...,14,261,1 576
47864,CaptainSparklez,@CaptainSparklez,2017-01-14,#WhatIWouldTellA15YearOldMe\nHere are the winn...,32,249,2 524
47865,Bitcoin News,@BTCTN,2017-01-11,Did Julian Assange Just Use the Bitcoin Blockc...,30,563,1 028
47866,WikiLeaks,@wikileaks,2017-01-11,Julian Assange Just Read Out a \n@Bitcoin\n Bl...,116,906,1 323
47867,Kim Dotcom,@KimDotcom,2017-01-01,#Bitcoin hits $1000\nAnd it's just the beginni...,47,391,842

# Translate all to English

In [13]:
import re
import langdetect
import translators as ts

In [14]:
for i in range(0, len(tweets)):
    tweets['Text'][i] = expand_contractions(tweets['Text'][i])
    
    tweets['Text'][i] = re.sub("[^A-Za-z]", " ", tweets['Text'][i])
    tweets['Text'][i] = re.sub(" +", " ",tweets['Text'][i])
    
    
    if len(tweets.loc[i, 'Text']) > 1:
        tweets.loc[i, 'lang'] = langdetect.detect(tweets.loc[i, 'Text'])

In [15]:
tweets_ = tweets

In [16]:
import translators as ts
import translators.server as tss
import warnings
warnings.filterwarnings('ignore')

tweets_ = tweets_[tweets_['lang'].notnull()]
tweets_ = tweets_.loc[tweets_['lang'] != '']
tweets_.reset_index(drop=True, inplace= True)
len(tweets_)

tweets_en = tweets_[tweets_['lang']=='en']
tweets_non_en = tweets_[tweets_['lang']!='en']
tweets_en.reset_index(drop=True, inplace= True)
tweets_non_en.reset_index(drop=True, inplace= True)

tweets_non_en['en'] = ''
tweets_non_en['en'][0] = tss.google(tweets_non_en['Text'][0], from_language=tweets_non_en['lang'][0], to_language='en')

In [17]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en
...,...,...,...,...,...,...,...,...
44388,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en
44389,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en
44390,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en
44391,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en
44392,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en

# Tonality Analysis

In [18]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en
...,...,...,...,...,...,...,...,...
44388,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en
44389,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en
44390,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en
44391,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en
44392,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en

In [19]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
import warnings
warnings.filterwarnings('ignore')

tweets_en['Text'] = tweets_en['Text'].astype(str)

sentiments = SentimentIntensityAnalyzer()
tweets_en["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in tweets_en["Text"]]
tweets_en["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in tweets_en["Text"]]
tweets_en["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in tweets_en["Text"]]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Lakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [20]:
tweets_en

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang,Positive,Negative,Neutral
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en,0.076,0.128,0.797
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en,0.000,0.683,0.317
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en,0.000,0.000,1.000
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en,0.000,0.212,0.788
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en,0.302,0.000,0.698
...,...,...,...,...,...,...,...,...,...,...,...
44388,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en,0.000,0.000,1.000
44389,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en,0.395,0.000,0.605
44390,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en,0.129,0.000,0.871
44391,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en,0.087,0.193,0.720
44392,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en,0.000,0.000,1.000

In [21]:
tweets_en.loc[tweets_en['Handle'] == '@elonmusk']

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang,Positive,Negative,Neutral
10570,Elon Musk,@elonmusk,2022-03-14,elonmusk saylor As a general principle for th...,4 056,"15,9 тыс.","58,3 тыс.",en,0.159,0.000,0.841
17999,Elon Musk,@elonmusk,2021-11-20,WSBChairman Bitcoin cures cancer,4 833,6 604,"40,3 тыс.",en,0.000,0.595,0.405
19565,Elon Musk,@elonmusk,2021-10-24,Filasophical ShibaInuHodler Out of curiosity ...,5 229,7 229,"34,9 тыс.",en,0.120,0.000,0.880
19566,Elon Musk,@elonmusk,2021-10-24,itsALLrisky TeslaGong Possibly Bitcoin was co...,725,864,5 225,en,0.123,0.124,0.752
24286,Elon Musk,@elonmusk,2021-07-28,heydave We have that many Bitcoin but close,3 213,1 413,"24,7 тыс.",en,0.000,0.000,1.000
25899,Elon Musk,@elonmusk,2021-06-25,not funny Bitcoin maxis,3 372,2 985,"57,2 тыс.",en,0.000,0.445,0.555
25900,Elon Musk,@elonmusk,2021-06-25,elonmusk jack Oh right Bitcoin haha,814,841,7 388,en,0.375,0.000,0.625
26608,Elon Musk,@elonmusk,2021-06-13,Cointelegraph This is inaccurate Tesla only s...,9 214,"12,7 тыс.","51,6 тыс.",en,0.241,0.000,0.759
27529,Elon Musk,@elonmusk,2021-06-05,lexfridman VitalikButerin I pretty much agree...,1 892,3 767,"23,3 тыс.",en,0.533,0.000,0.467
28391,Elon Musk,@elonmusk,2021-05-20,TeslaGong wintonARK Bitcoin hashing aka minin...,1 458,1 063,5 358,en,0.159,0.000,0.841
31492,Elon Musk,@elonmusk,2021-03-24,Pay by Bitcoin capability available outside US...,2 943,9 003,"132,1 тыс.",en,0.000,0.135,0.865
31493,Elon Musk,@elonmusk,2021-03-24,Tesla is using only internal open source softw...,4 432,22 тыс.,"168,1 тыс.",en,0.042,0.000,0.958
31496,Elon Musk,@elonmusk,2021-03-24,You can now buy a Tesla with Bitcoin,"33,8 тыс.","127,7 тыс.","839,2 тыс.",en,0.000,0.000,1.000
32080,Elon Musk,@elonmusk,2021-03-12,BTC Bitcoin is an anagram of TBC The Boring Co...,11 тыс.,"18,2 тыс.","227,9 тыс.",en,0.000,0.173,0.827
33209,Elon Musk,@elonmusk,2021-02-19,elonmusk business To be clear I am not an inv...,1 978,6 944,"32,7 тыс.",en,0.105,0.124,0.771
33211,Elon Musk,@elonmusk,2021-02-19,business Tesla s action is not directly refle...,897,3 501,"25,7 тыс.",en,0.074,0.093,0.833
36077,Elon Musk,@elonmusk,2020-12-20,Bitcoin is almost as bs as fiat money,7 624,"12,7 тыс.","129,3 тыс.",en,0.000,0.000,1.000
36085,Elon Musk,@elonmusk,2020-12-20,Bitcoin is my safe word,6 257,"21,4 тыс.","222,1 тыс.",en,0.420,0.000,0.580
39045,Elon Musk,@elonmusk,2020-05-15,jk rowling Pretty much although massive curre...,688,3 203,"14,1 тыс.",en,0.271,0.000,0.729
39273,Elon Musk,@elonmusk,2020-05-01,Bitcoin How much for some anime Bitcoin,727,2 517,"17,1 тыс.",en,0.000,0.000,1.000
39274,Elon Musk,@elonmusk,2020-05-01,Bitcoin,152,182,4 785,en,0.000,0.000,1.000
40010,Elon Musk,@elonmusk,2020-01-10,Bitcoin is not my safe word,2 579,8 979,"111,7 тыс.",en,0.000,0.325,0.675

### Reading BTC Data

In [22]:
btc_data = pd.read_csv(r'C:\Users\Lakshi\Downloads\Cryptomatter-project-data-preprocessing\Cryptomatter-project-data-preprocessing\Data\BTC_data.csv', delimiter=";")
btc_data['Date'] = pd.to_datetime(btc_data['Date'], infer_datetime_format=True, utc=True, errors='ignore')
btc_data['Date'] = btc_data.Date.dt.date
btc_data

            Date    MarketCap  TradeVolume  ClosePrice
0     2013-12-31   9358690000     23448600      767.74
1     2014-01-02   9417080000     16837800      772.53
2     2014-01-03  10062400000     54171500      825.47
3     2014-01-04  10351000000     36344700      849.14
4     2014-01-05  11207500000     62414600      919.41
...          ...          ...          ...         ...
3121  2022-11-16  3,24608E+11  28676300000    16890.50
3122  2022-11-17  3,20099E+11  26922000000    16689.40
3123  2022-11-18  3,21287E+11  22011300000    16718.40
3124  2022-11-19  3,20877E+11  20942200000    16707.00
3125  2022-11-20  3,21151E+11  10844500000    16712.70

[3126 rows x 4 columns]

### Merging sentiment and BTC data

In [23]:
df_merged = tweets_en.merge(btc_data, on='Date')
#df_merged = df_merged[['Date','Text','Reply_cnt','Retweet_cnt','Like_cnt','Positive','Negative','Neutral','ClosePrice']]
df_merged = df_merged[['Date','Positive','Negative','Neutral','ClosePrice']]
display(df_merged)

             Date  Positive  Negative  Neutral  ClosePrice
0      2022-11-20     0.000     0.000    1.000   16712.700
1      2022-11-20     0.182     0.085    0.733   16712.700
2      2022-11-20     0.000     0.000    1.000   16712.700
3      2022-11-20     0.233     0.183    0.583   16712.700
4      2022-11-20     0.118     0.291    0.591   16712.700
...           ...       ...       ...      ...         ...
43438  2017-01-14     0.000     0.000    1.000     817.825
43439  2017-01-14     0.395     0.000    0.605     817.825
43440  2017-01-11     0.129     0.000    0.871     784.278
43441  2017-01-11     0.087     0.193    0.720     784.278
43442  2017-01-01     0.000     0.000    1.000     998.050

[43443 rows x 5 columns]

In [34]:
# #type(df_merged['Date'])
# df_temp=df_merged.head(78)
# df_temp = df_temp["ClosePrice"].mean()
# print(df_temp)

### Reading BTC Binance Data

In [25]:
btc_binance = pd.read_csv(r'C:\Users\Lakshi\Downloads\Cryptomatter-project-data-preprocessing\Cryptomatter-project-data-preprocessing\\Data\BTC_Binance.csv', delimiter=";")
btc_binance.rename(columns={'UNIX timestamp': 'Date'}, inplace=True)
btc_binance['Date']=btc_binance['Date'].str.replace(',', '.').astype(float)
btc_binance.Date = pd.to_datetime(btc_binance.Date, unit='ms')
btc_binance['Date'] = btc_binance.Date.dt.date
btc_binance

,first_currency,second_currency,Date,open,high,low,close,volume
0,BTC,USDT,2017-08-17,4261.48,4485.39,4200.74,4285.08,795.150
1,BTC,USDT,2017-08-18,4285.08,4371.52,3938.77,4108.37,1199.890
2,BTC,USDT,2017-08-20,4108.37,4184.69,3850.00,4139.98,381.310
3,BTC,USDT,2017-08-20,4120.98,4211.08,4032.62,4086.29,467.083
4,BTC,USDT,2017-08-22,4069.13,4119.62,3911.79,4016.00,691.743
...,...,...,...,...,...,...,...,...
1918,BTC,USDT,2022-11-18,16661.60,16751.00,16410.70,16692.60,228039.000
1919,BTC,USDT,2022-11-19,16692.60,17011.00,16546.00,16700.40,214224.000
1920,BTC,USDT,2022-11-19,16699.40,16822.40,16553.50,16700.70,104963.000
1921,BTC,USDT,2022-11-21,16700.70,16753.30,16180.00,16280.20,154842.000
1922,BTC,USDT,2022-11-22,16279.50,16319.00,15476.00,15781.30,324097.000

In [26]:
df_merged_binance = tweets_en.merge(btc_binance, on='Date')
df_merged_binance = df_merged_binance[['Date','Positive','Negative','Neutral','close']]
display(df_merged_binance)

             Date  Positive  Negative  Neutral     close
0      2022-11-22     0.000     0.000    1.000  15781.30
1      2022-11-22     0.125     0.063    0.812  15781.30
2      2022-11-22     0.000     0.000    1.000  15781.30
3      2022-11-22     0.101     0.198    0.702  15781.30
4      2022-11-22     0.000     0.000    1.000  15781.30
...           ...       ...       ...      ...       ...
44313  2017-08-22     0.055     0.288    0.657   4016.00
44314  2017-08-22     0.441     0.000    0.559   4016.00
44315  2017-08-22     0.000     0.000    1.000   4016.00
44316  2017-08-17     0.000     0.000    1.000   4285.08
44317  2017-08-17     0.000     0.065    0.935   4285.08

[44318 rows x 5 columns]

In [27]:
df_merged_binance.dtypes

Date         object
Positive    float64
Negative    float64
Neutral     float64
close       float64
dtype: object

In [28]:
df= df_merged.merge(btc_binance[['Date', 'close']], on='Date', how='right')

In [29]:
#Checking for missing values
df.isna().sum()

Date            0
Positive      155
Negative      155
Neutral       155
ClosePrice    155
close           0
dtype: int64

In [30]:
#Dropping the rows with missing values
df.dropna(axis=0, inplace=True)

In [31]:
df.isna().sum()   #Check if any remaining missing values

Date          0
Positive      0
Negative      0
Neutral       0
ClosePrice    0
close         0
dtype: int64

In [32]:
df_new = df[["Date","Positive","Negative","Neutral",'close']]

In [33]:
df_new

             Date  Positive  Negative  Neutral     close
0      2017-08-17     0.000     0.000    1.000   4285.08
1      2017-08-17     0.000     0.065    0.935   4285.08
5      2017-08-22     0.055     0.288    0.657   4016.00
6      2017-08-22     0.441     0.000    0.559   4016.00
7      2017-08-22     0.000     0.000    1.000   4016.00
...           ...       ...       ...      ...       ...
43888  2022-11-19     0.151     0.000    0.849  16700.70
43889  2022-11-19     0.000     0.163    0.837  16700.70
43890  2022-11-19     0.200     0.000    0.800  16700.70
43891  2022-11-19     0.274     0.369    0.357  16700.70
43892  2022-11-19     0.000     0.000    1.000  16700.70

[43740 rows x 5 columns]

In [34]:
df_model=df_new.groupby(['Date']).mean()

In [35]:
df_model

            Positive  Negative   Neutral      close
Date
2017-08-17  0.000000  0.032500  0.967500   4285.080
2017-08-22  0.165333  0.096000  0.738667   4016.000
2017-08-23  0.115333  0.066000  0.818667   4077.005
2017-08-25  0.000000  0.189500  0.810500   4316.010
2017-08-29  0.083500  0.020250  0.896250   4587.480
...              ...       ...       ...        ...
2022-11-13  0.067154  0.081846  0.851077  16570.950
2022-11-14  0.116170  0.050962  0.832868  16619.500
2022-11-16  0.105100  0.046940  0.847980  16781.700
2022-11-18  0.090377  0.068754  0.840934  16692.600
2022-11-19  0.120398  0.067739  0.811852  16700.550

[1115 rows x 4 columns]

### Modelling

In [36]:
X = df_model
y = pd.DataFrame(df_model['close'])

Test Train Split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
#Using MinMax Scaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [40]:
#Scaling y_train_scaled and y_test_scaled
scaler = MinMaxScaler()
y_train_scaled = scaler.fit_transform(y_train)
y_test_scaled = scaler.transform(y_test)

#### XG Boost

In [52]:
metric_xgb = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    #Using seg-learn to create time window for prediction
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    n_est=np.arange(100,1000,50)
    mse_n_est=[]
    for i in n_est:
              model_tuned=XGBRegressor(random_state=1000,
                             n_estimators=i).fit(X_train_flattened,y_train_rolled)
              pred=model_tuned.predict(X_test_flattened)
              mse_n_est.append(metrics.mean_squared_error(y_test_rolled,pred))
    learning_r=[0.01,0.05,0.1,0.15,0.2,0.3]
    mse_lr=[]
    for i in learning_r:
              model_tuned=XGBRegressor(random_state=1000,
              learning_rate=i,).fit(X_train_flattened,y_train_rolled)
              pred=model_tuned.predict(X_test_flattened)
              mse_lr.append(metrics.mean_squared_error(y_test_rolled,pred))
        #Optimised Model
    model_xgb_tuned=XGBRegressor(learning_rate=learning_r[mse_lr.index(min(mse_lr))],random_state=4000,n_estimators=n_est[mse_n_est.index(min(mse_n_est))],
                    max_depth=2).fit(X_train_flattened,y_train_rolled)
    pred_train=model_xgb_tuned.predict(X_train_flattened)
    pred_test=model_xgb_tuned.predict(X_test_flattened)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_xgb_tuned={'Classical Model':['XGboost Regressor_Tuned'],
                      'Time window' : l,
                      'MSE Train':mse_train,
                      'MSE Test':mse_test,
                      'MAE Train':mae_train,
                      'MAE Test':mae_test}
    metric_xgb_tune=pd.DataFrame(metric_xgb_tuned)
    metric_xgb = pd.concat([metric_xgb_tune,metric_xgb],ignore_index=True)
    metric_xgb

In [53]:
metric_xgb

,Classical Model,Time window,MSE Train,MSE Test,MAE Train,MAE Test
0,XGboost Regressor_Tuned,14,7.258843e+08,7.397504e+08,7.258843e+08,7.397504e+08
1,XGboost Regressor_Tuned,13,7.250835e+08,7.367314e+08,7.250835e+08,7.367314e+08
2,XGboost Regressor_Tuned,12,7.242801e+08,7.402134e+08,7.242801e+08,7.402134e+08
3,XGboost Regressor_Tuned,11,7.234886e+08,7.372247e+08,7.234886e+08,7.372247e+08
4,XGboost Regressor_Tuned,10,7.252399e+08,7.355439e+08,7.252399e+08,7.355439e+08
5,XGboost Regressor_Tuned,9,7.255909e+08,7.324482e+08,7.255909e+08,7.324482e+08
6,XGboost Regressor_Tuned,8,7.292985e+08,7.294446e+08,7.292985e+08,7.294446e+08
7,XGboost Regressor_Tuned,7,7.298321e+08,7.261963e+08,7.298321e+08,7.261963e+08
8,XGboost Regressor_Tuned,6,7.290939e+08,7.295818e+08,7.290939e+08,7.295818e+08
9,XGboost Regressor_Tuned,5,7.282895e+08,7.265648e+08,7.282895e+08,7.265648e+08
10,XGboost Regressor_Tuned,4,7.284296e+08,7.345322e+08,7.284296e+08,7.345322e+08
11,XGboost Regressor_Tuned,3,7.276804e+08,7.367544e+08,7.276804e+08,7.367544e+08

### Random Forest

In [54]:
metric_rf = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    #Random forest parameter optimization uses grid search
    params={'max_depth':list(np.arange(3,10,2)),
     'n_estimators':[50,100,150,200],}
    model=RandomForestRegressor()
    gsearch=GridSearchCV(estimator=model,param_grid=params,cv=5).fit(X_train_flattened,y_train_rolled)
    rf_model_tuned=RandomForestRegressor(n_estimators=gsearch.best_params_.get('n_estimators'),max_depth=gsearch.best_params_.get('max_depth')).fit(X_train_flattened,y_train_rolled)
    pred_train=rf_model_tuned.predict(X_train_flattened)
    pred_test=rf_model_tuned.predict(X_test_flattened)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_rf_tuned={'Classical Model':['Random Forest_Tuned'],
                     'Time window' : l,
                     'MSE Train':mse_train,
                     'MSE Test':mse_test,
                     'MAE Train':mae_train,
                     'MAE Test':mae_test}
    rf_model_tune=pd.DataFrame(metric_rf_tuned)
    metric_rf = pd.concat([rf_model_tune,metric_rf],ignore_index=True)
    metric_rf

In [55]:
metric_rf

,Classical Model,Time window,MSE Train,MSE Test,MAE Train,MAE Test
0,Random Forest_Tuned,14,7.258850e+08,7.397506e+08,7.258850e+08,7.397506e+08
1,Random Forest_Tuned,13,7.250858e+08,7.367319e+08,7.250858e+08,7.367319e+08
2,Random Forest_Tuned,12,7.242808e+08,7.402139e+08,7.242808e+08,7.402139e+08
3,Random Forest_Tuned,11,7.234886e+08,7.372250e+08,7.234886e+08,7.372250e+08
4,Random Forest_Tuned,10,7.252416e+08,7.355443e+08,7.252416e+08,7.355443e+08
5,Random Forest_Tuned,9,7.255922e+08,7.324486e+08,7.255922e+08,7.324486e+08
6,Random Forest_Tuned,8,7.292994e+08,7.294450e+08,7.292994e+08,7.294450e+08
7,Random Forest_Tuned,7,7.298330e+08,7.261967e+08,7.298330e+08,7.261967e+08
8,Random Forest_Tuned,6,7.290952e+08,7.295821e+08,7.290952e+08,7.295821e+08
9,Random Forest_Tuned,5,7.282900e+08,7.265650e+08,7.282900e+08,7.265650e+08
10,Random Forest_Tuned,4,7.284303e+08,7.345325e+08,7.284303e+08,7.345325e+08
11,Random Forest_Tuned,3,7.276813e+08,7.367546e+08,7.276813e+08,7.367546e+08

### LSTM Model

In [56]:
LSTM_CELL_SIZE= 10
BATCH_SIZE = 100
EPOCHS = 5
DROPOUT_RATE=0.001

In [57]:
metric_lstm_f = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    # Building the LSTM model here!
    model_lstm = Sequential()
    model_lstm.add(LSTM(units=LSTM_CELL_SIZE,activation = 'relu',input_shape=(l,4)))
    model_lstm.add(Dense (5, activation = 'relu'))
    model_lstm.add(Dropout(DROPOUT_RATE))
    model_lstm.add(Dense (1))
    model_lstm.compile(loss='mean_squared_error', optimizer=Adam(learning_rate = 0.02),metrics=["accuracy"])
    history = model_lstm.fit(X_train_rolled, y_train_rolled,validation_data=(X_test_rolled, y_test_rolled), epochs=EPOCHS,batch_size=BATCH_SIZE,verbose =1)
    pred_train=model_lstm.predict(X_train_rolled)
    pred_test=model_lstm.predict(X_test_rolled)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_lstm={'Model':['LSTM'],
            "Time Window" : l,
            'MSE Train':mse_train,
            'MAE Train':mae_train,
            'MSE Test':mse_test,
            'MAE Test':mae_test}
    metric_lstm=pd.DataFrame(metric_lstm)
    metric_lstm_f = pd.concat([metric_lstm,metric_lstm_f],ignore_index=True)
    metric_lstm_f

Epoch 1/5
9/9 [==============================] - 7s 77ms/step - loss: 0.1498 - accuracy: 0.0011 - val_loss: 0.0833 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0862 - accuracy: 0.0011 - val_loss: 0.0815 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0811 - accuracy: 0.0011 - val_loss: 0.0787 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0776 - accuracy: 0.0011 - val_loss: 0.0787 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0777 - val_accuracy: 0.0000e+00
28/28 [==============================] - 1s 3ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 46ms/step - loss: 0.1110 - accuracy: 0.0011 - val_loss: 0.0768 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0817 - accuracy: 0.0011 - val_loss: 0.0794 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0793 - accuracy: 0.0011 - val_loss: 0.0786 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0776 - accuracy: 0.0011 - val_loss: 0.0774 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0779 - accuracy: 0.0011 - val_loss: 0.0770 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 4ms/step
Epoch 1/5
9/9 [==============================] - 2s 49ms/step - loss: 0.1023 - accuracy: 0.0011 - val_loss: 0.0790 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 7ms/step - loss: 0.0805 - accuracy: 0.0011 - val_loss: 0.0765 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0800 - accuracy: 0.0011 - val_loss: 0.0767 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0778 - accuracy: 0.0011 - val_loss: 0.0767 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 9ms/step - loss: 0.0775 - accuracy: 0.0011 - val_loss: 0.0766 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 2ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 48ms/step - loss: 0.0877 - accuracy: 0.0011 - val_loss: 0.0836 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0808 - accuracy: 0.0011 - val_loss: 0.0793 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 8ms/step - loss: 0.0784 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0780 - accuracy: 0.0011 - val_loss: 0.0775 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0780 - accuracy: 0.0011 - val_loss: 0.0774 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 46ms/step - loss: 0.1068 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0822 - accuracy: 0.0011 - val_loss: 0.0781 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0784 - accuracy: 0.0011 - val_loss: 0.0786 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 14ms/step - loss: 0.0785 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0781 - accuracy: 0.0011 - val_loss: 0.0774 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 54ms/step - loss: 0.1021 - accuracy: 0.0011 - val_loss: 0.0795 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0795 - accuracy: 0.0011 - val_loss: 0.0784 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0781 - accuracy: 0.0011 - val_loss: 0.0781 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0780 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0779 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 4ms/step
Epoch 1/5
9/9 [==============================] - 2s 45ms/step - loss: 0.0867 - accuracy: 0.0011 - val_loss: 0.0804 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0794 - accuracy: 0.0011 - val_loss: 0.0782 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0779 - accuracy: 0.0011 - val_loss: 0.0770 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0776 - accuracy: 0.0011 - val_loss: 0.0771 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0779 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 2ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 39ms/step - loss: 0.1169 - accuracy: 0.0011 - val_loss: 0.0807 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 10ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0782 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0781 - accuracy: 0.0011 - val_loss: 0.0778 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0773 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0776 - accuracy: 0.0011 - val_loss: 0.0777 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 2ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 46ms/step - loss: 0.0855 - accuracy: 0.0011 - val_loss: 0.0821 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 11ms/step - loss: 0.0800 - accuracy: 0.0011 - val_loss: 0.0781 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0783 - accuracy: 0.0011 - val_loss: 0.0783 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0777 - accuracy: 0.0011 - val_loss: 0.0779 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 14ms/step - loss: 0.0776 - accuracy: 0.0011 - val_loss: 0.0780 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 38ms/step - loss: 0.0944 - accuracy: 0.0011 - val_loss: 0.0787 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0785 - accuracy: 0.0011 - val_loss: 0.0796 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 9ms/step - loss: 0.0779 - accuracy: 0.0011 - val_loss: 0.0786 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0772 - accuracy: 0.0011 - val_loss: 0.0792 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0781 - accuracy: 0.0011 - val_loss: 0.0783 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 767us/step
Epoch 1/5

9/9 [==============================] - 2s 47ms/step - loss: 0.1026 - accuracy: 0.0011 - val_loss: 0.0795 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0843 - accuracy: 0.0011 - val_loss: 0.0810 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0794 - accuracy: 0.0011 - val_loss: 0.0806 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 15ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0785 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0777 - accuracy: 0.0011 - val_loss: 0.0786 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 3ms/step
7/7 [==============================] - 0s 3ms/step
Epoch 1/5
9/9 [==============================] - 2s 42ms/step - loss: 0.0947 - accuracy: 0.0011 - val_loss: 0.0843 - val_accuracy: 0.0000e+00
Epoch 2/5
9/9 [==============================] - 0s 12ms/step - loss: 0.0807 - accuracy: 0.0011 - val_loss: 0.0784 - val_accuracy: 0.0000e+00
Epoch 3/5
9/9 [==============================] - 0s 13ms/step - loss: 0.0782 - accuracy: 0.0011 - val_loss: 0.0790 - val_accuracy: 0.0000e+00
Epoch 4/5
9/9 [==============================] - 0s 16ms/step - loss: 0.0774 - accuracy: 0.0011 - val_loss: 0.0790 - val_accuracy: 0.0000e+00
Epoch 5/5
9/9 [==============================] - 0s 14ms/step - loss: 0.0773 - accuracy: 0.0011 - val_loss: 0.0783 - val_accuracy: 0.0000e+00
28/28 [==============================] - 0s 4ms/step
7/7 [==============================] - 0s 4ms/step

In [58]:
metric_lstm_f

   Model  Time Window     MSE Train     MAE Train      MSE Test      MAE Test
0   LSTM           14  7.258854e+08  7.258854e+08  7.397502e+08  7.397502e+08
1   LSTM           13  7.250871e+08  7.250871e+08  7.367324e+08  7.367324e+08
2   LSTM           12  7.242816e+08  7.242816e+08  7.402140e+08  7.402140e+08
3   LSTM           11  7.234905e+08  7.234905e+08  7.372254e+08  7.372254e+08
4   LSTM           10  7.252419e+08  7.252419e+08  7.355439e+08  7.355439e+08
5   LSTM            9  7.255939e+08  7.255939e+08  7.324497e+08  7.324497e+08
6   LSTM            8  7.293003e+08  7.293003e+08  7.294454e+08  7.294454e+08
7   LSTM            7  7.298331e+08  7.298331e+08  7.261964e+08  7.261964e+08
8   LSTM            6  7.290960e+08  7.290960e+08  7.295824e+08  7.295824e+08
9   LSTM            5  7.282903e+08  7.282903e+08  7.265647e+08  7.265647e+08
10  LSTM            4  7.284305e+08  7.284305e+08  7.345321e+08  7.345321e+08
11  LSTM            3  7.276817e+08  7.276817e+08  7.367547e+08  7.367547e+08

### Sentiment heuristic

In [66]:
tweets_en2 = pd.read_csv(r'C:\Users\Lakshi\Desktop\Tweets_EN.csv')

In [67]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
import warnings
warnings.filterwarnings('ignore')

tweets_en2['Text'] = tweets_en2['Text'].astype(str)

sentiments = SentimentIntensityAnalyzer()
tweets_en2["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in tweets_en2["Text"]]
tweets_en2["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in tweets_en2["Text"]]
tweets_en2["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in tweets_en2["Text"]]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Lakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [68]:
tweets_en2

,Username,Handle,Date,Text,Reply_cnt,Retweet_cnt,Like_cnt,lang,Positive,Negative,Neutral
0,Pierre,@pierre_crypt0,2022-11-26,Satoshi created Bitcoin Fast forward years lat...,37,49,511,en,0.076,0.128,0.797
1,Jason A. Williams,@GoingParabolic,2022-11-26,Bitcoin is dead,224,37,567,en,0.000,0.683,0.317
2,sunnydecree,@sunnydecree,2022-11-26,Bitcoin Just Bitcoin Not Blockchain and not C...,121,42,520,en,0.000,0.000,1.000
3,Will Clemente,@WClementeIII,2022-11-26,Anyone saying Bitcoin has no more narratives t...,81,24,527,en,0.000,0.212,0.788
4,Bitcoin Magazine,@BitcoinMagazine,2022-11-26,Smoothie shop accepting bitcoin in El Salvador,182,387,2 057,en,0.302,0.000,0.698
...,...,...,...,...,...,...,...,...,...,...,...
44381,Charlie,@MoistCr1TiKaL,2017-01-14,WhatIWouldITellA YearOldMe invest everything ...,14,261,1 576,en,0.000,0.000,1.000
44382,CaptainSparklez,@CaptainSparklez,2017-01-14,WhatIWouldTellA YearOldMe Here are the winnin...,32,249,2 524,en,0.395,0.000,0.605
44383,Bitcoin News,@BTCTN,2017-01-11,Did an Assange Just Use the Bitcoin Blockchain...,30,563,1 028,en,0.129,0.000,0.871
44384,WikiLeaks,@wikileaks,2017-01-11,an Assange Just Read Out a Bitcoin Block Hash ...,116,906,1 323,en,0.087,0.193,0.720
44385,Kim Dotcom,@KimDotcom,2017-01-01,Bitcoin hits And just the beginning,47,391,842,en,0.000,0.000,1.000

### Twitter Feature Data Cleaning

In [69]:
tweets_en2['Reply_cnt']=tweets_en2['Reply_cnt'].str.replace(' ','')
tweets_en2['Retweet_cnt']=tweets_en2['Retweet_cnt'].str.replace(' ','')
tweets_en2['Like_cnt']=tweets_en2['Like_cnt'].str.replace(' ','')

tweets_en2['Reply_cnt']=tweets_en2['Reply_cnt'].str.replace(',','')
tweets_en2['Retweet_cnt']=tweets_en2['Retweet_cnt'].str.replace(',','')
tweets_en2['Like_cnt']=tweets_en2['Like_cnt'].str.replace(',','')

In [70]:
tweets_en2['Reply_cnt']=tweets_en2['Reply_cnt'].str.replace('тыс.','000')
tweets_en2['Retweet_cnt']=tweets_en2['Retweet_cnt'].str.replace('тыс.','000')
tweets_en2['Like_cnt']=tweets_en2['Like_cnt'].str.replace('тыс.','000')

In [71]:
tweets_en2[tweets_en2['Like_cnt'].str.isnumeric()==False]

Empty DataFrame
Columns: [Username, Handle, Date, Text, Reply_cnt, Retweet_cnt, Like_cnt, lang, Positive, Negative, Neutral]
Index: []

In [72]:
tweets_en2['Reply_cnt']=tweets_en2['Reply_cnt'].astype(float)
tweets_en2['Retweet_cnt']=tweets_en2['Retweet_cnt'].astype(float)
tweets_en2['Like_cnt']=tweets_en2['Like_cnt'].astype(int)

In [73]:
tweets_en2.Date = pd.to_datetime(tweets_en2.Date)
tweets_en2['Date'] = tweets_en2.Date.dt.date

### Merging sentiment and BTC data

In [74]:
df_merged = tweets_en2.merge(btc_data, on='Date', how='inner')
df_merged = df_merged[['Date','Positive','Negative','Neutral','ClosePrice', 'Reply_cnt', 'Retweet_cnt', 'Like_cnt']]
display(df_merged)

,Date,Positive,Negative,Neutral,ClosePrice,Reply_cnt,Retweet_cnt,Like_cnt
0,2022-11-20,0.000,0.000,1.000,16712.700,65.0,100.0,1402
1,2022-11-20,0.182,0.085,0.733,16712.700,131.0,160.0,1894
2,2022-11-20,0.000,0.000,1.000,16712.700,430.0,75.0,1192
3,2022-11-20,0.233,0.183,0.583,16712.700,46.0,57.0,1064
4,2022-11-20,0.118,0.291,0.591,16712.700,297.0,279.0,3169
...,...,...,...,...,...,...,...,...
43431,2017-01-14,0.000,0.000,1.000,817.825,14.0,261.0,1576
43432,2017-01-14,0.395,0.000,0.605,817.825,32.0,249.0,2524
43433,2017-01-11,0.129,0.000,0.871,784.278,30.0,563.0,1028
43434,2017-01-11,0.087,0.193,0.720,784.278,116.0,906.0,1323
43435,2017-01-01,0.000,0.000,1.000,998.050,47.0,391.0,842

In [75]:
df_merged['NumOfTweets'] = df_merged.groupby('Date')['Date'].transform('count')
df_merged['Std_Positive'] = df_merged.groupby('Date')['Positive'].transform('std')
df_merged['Std_Negative'] = df_merged.groupby('Date')['Negative'].transform('std')
df_merged['Std_Neutral'] = df_merged.groupby('Date')['Neutral'].transform('std')
df_merged['Tweet_Engagement'] = df_merged['Reply_cnt']*df_merged['Retweet_cnt']*df_merged['Like_cnt']/10**7

In [76]:
temp=df_merged.groupby(['Date'])
pos_avg=[]
neg_avg=[]
neu_avg=[]
close=[]
std_Threshold = 0.1

for date in df_merged.Date.unique():
    Temp = temp.get_group(date)
    close.append(Temp['ClosePrice'].iat[0])
    if Temp['NumOfTweets'].iat[0] == 1:
        pos_avg.append(Temp['Positive'].iat[0])
        neg_avg.append(Temp['Negative'].iat[0])
        neu_avg.append(Temp['Neutral'].iat[0])
        
    else:
        if ((Temp['Std_Positive'].iat[0] < std_Threshold) & (Temp['Std_Negative'].iat[0] < std_Threshold) & (Temp['Std_Neutral'].iat[0] < std_Threshold)):
            pos_avg.append(Temp['Positive'].mean())
            neg_avg.append(Temp['Negative'].mean())
            neu_avg.append(Temp['Neutral'].mean())
        else:
            pos_avg.append(Temp['Positive'][Temp['Tweet_Engagement']==Temp['Tweet_Engagement'].max()].iat[0])
            neg_avg.append(Temp['Negative'][Temp['Tweet_Engagement']==Temp['Tweet_Engagement'].max()].iat[0])
            neu_avg.append(Temp['Neutral'][Temp['Tweet_Engagement']==Temp['Tweet_Engagement'].max()].iat[0])

In [77]:
sentiment_heuristic1 = pd.DataFrame(list(zip(df_merged.Date.unique().tolist(), pos_avg, neg_avg, neu_avg, close)),
             columns =['Date', 'Pos', 'Neg', 'Neu', 'Close'])

In [85]:
sentiment_heuristic1.set_index("Date",inplace=True)

In [86]:
sentiment_heuristic1

              Pos    Neg    Neu      Close
Date
2022-11-20  0.119  0.000  0.881  16712.700
2022-11-19  0.193  0.207  0.600  16707.000
2022-11-18  0.083  0.203  0.714  16718.400
2022-11-17  0.000  0.000  1.000  16689.400
2022-11-16  0.000  0.000  1.000  16890.500
...           ...    ...    ...        ...
2017-03-17  0.425  0.050  0.525   1074.090
2017-02-19  0.095  0.000  0.905   1053.500
2017-01-14  0.395  0.000  0.605    817.825
2017-01-11  0.087  0.193  0.720    784.278
2017-01-01  0.000  0.000  1.000    998.050

[1804 rows x 4 columns]

In [87]:
X = sentiment_heuristic1
y = pd.DataFrame(sentiment_heuristic1['Close'])

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [89]:
from sklearn.preprocessing import MinMaxScaler

In [90]:
#Using MinMax Scaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [91]:
#Scaling y_train_scaled and y_test_scaled
scaler = MinMaxScaler()
y_train_scaled = scaler.fit_transform(y_train)
y_test_scaled = scaler.transform(y_test)

### XG Boost

In [99]:
metric_xgb_2 = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    #Using seg-learn to create time window for prediction
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    n_est=np.arange(100,1000,50)
    mse_n_est=[]
    for i in n_est:
              model_tuned=XGBRegressor(random_state=1000,
                             n_estimators=i).fit(X_train_flattened,y_train_rolled)
              pred=model_tuned.predict(X_test_flattened)
              mse_n_est.append(metrics.mean_squared_error(y_test_rolled,pred))
    learning_r=[0.01,0.05,0.1,0.15,0.2,0.3]
    mse_lr=[]
    for i in learning_r:
              model_tuned=XGBRegressor(random_state=1000,
              learning_rate=i,).fit(X_train_flattened,y_train_rolled)
              pred=model_tuned.predict(X_test_flattened)
              mse_lr.append(metrics.mean_squared_error(y_test_rolled,pred))
        #Optimised Model
    model_xgb_tuned=XGBRegressor(learning_rate=learning_r[mse_lr.index(min(mse_lr))],random_state=4000,n_estimators=n_est[mse_n_est.index(min(mse_n_est))],
                    max_depth=2).fit(X_train_flattened,y_train_rolled)
    pred_train=model_xgb_tuned.predict(X_train_flattened)
    pred_test=model_xgb_tuned.predict(X_test_flattened)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_xgb_tuned={'Classical Model':['XGboost Regressor'],
                      'Time window' : l,
                      'MSE Train':mse_train,
                      'MSE Test':mse_test,
                      'MAE Train':mae_train,
                      'MAE Test':mae_test}
    metric_xgb_tune=pd.DataFrame(metric_xgb_tuned)
    metric_xgb_2 = pd.concat([metric_xgb_tune,metric_xgb_2],ignore_index=True)
    metric_xgb_2

In [100]:
metric_xgb_2

,Classical Model,Time window,MSE Train,MSE Test,MAE Train,MAE Test
0,XGboost Regressor,14,6.832811e+08,7.747570e+08,6.832811e+08,7.747570e+08
1,XGboost Regressor,13,6.843557e+08,7.753494e+08,6.843557e+08,7.753494e+08
2,XGboost Regressor,12,6.846481e+08,7.767522e+08,6.846481e+08,7.767522e+08
3,XGboost Regressor,11,6.856866e+08,7.747416e+08,6.856866e+08,7.747416e+08
4,XGboost Regressor,10,6.868557e+08,7.817930e+08,6.868557e+08,7.817930e+08
5,XGboost Regressor,9,6.864155e+08,7.831617e+08,6.864155e+08,7.831617e+08
6,XGboost Regressor,8,6.865293e+08,7.875225e+08,6.865293e+08,7.875225e+08
7,XGboost Regressor,7,6.881433e+08,7.853979e+08,6.881433e+08,7.853979e+08
8,XGboost Regressor,6,6.877333e+08,7.895067e+08,6.877333e+08,7.895067e+08
9,XGboost Regressor,5,6.899751e+08,7.876864e+08,6.899751e+08,7.876864e+08
10,XGboost Regressor,4,6.895245e+08,7.858302e+08,6.895245e+08,7.858302e+08
11,XGboost Regressor,3,6.891334e+08,7.837800e+08,6.891334e+08,7.837800e+08

### Random Forest

In [101]:
metric_rf_2 = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    #Random forest parameter optimization uses grid search
    params={'max_depth':list(np.arange(3,10,2)),
     'n_estimators':[50,100,150,200],}
    model=RandomForestRegressor()
    gsearch=GridSearchCV(estimator=model,param_grid=params,cv=5).fit(X_train_flattened,y_train_rolled)
    rf_model_tuned=RandomForestRegressor(n_estimators=gsearch.best_params_.get('n_estimators'),max_depth=gsearch.best_params_.get('max_depth')).fit(X_train_flattened,y_train_rolled)
    pred_train=rf_model_tuned.predict(X_train_flattened)
    pred_test=rf_model_tuned.predict(X_test_flattened)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_rf_tuned={'Classical Model':['Random Forest_Tuned'],
                     'Time window' : l,
                     'MSE Train':mse_train,
                     'MSE Test':mse_test,
                     'MAE Train':mae_train,
                     'MAE Test':mae_test}
    rf_model_tune=pd.DataFrame(metric_rf_tuned)
    metric_rf_2 = pd.concat([rf_model_tune,metric_rf_2],ignore_index=True)
    metric_rf_2

In [102]:
metric_rf_2

,Classical Model,Time window,MSE Train,MSE Test,MAE Train,MAE Test
0,Random Forest_Tuned,14,6.832814e+08,7.747571e+08,6.832814e+08,7.747571e+08
1,Random Forest_Tuned,13,6.843560e+08,7.753495e+08,6.843560e+08,7.753495e+08
2,Random Forest_Tuned,12,6.846509e+08,7.767554e+08,6.846509e+08,7.767554e+08
3,Random Forest_Tuned,11,6.856883e+08,7.747434e+08,6.856883e+08,7.747434e+08
4,Random Forest_Tuned,10,6.868586e+08,7.817962e+08,6.868586e+08,7.817962e+08
5,Random Forest_Tuned,9,6.864184e+08,7.831647e+08,6.864184e+08,7.831647e+08
6,Random Forest_Tuned,8,6.865297e+08,7.875226e+08,6.865297e+08,7.875226e+08
7,Random Forest_Tuned,7,6.881436e+08,7.853980e+08,6.881436e+08,7.853980e+08
8,Random Forest_Tuned,6,6.877335e+08,7.895067e+08,6.877335e+08,7.895067e+08
9,Random Forest_Tuned,5,6.899753e+08,7.876864e+08,6.899753e+08,7.876864e+08
10,Random Forest_Tuned,4,6.895274e+08,7.858333e+08,6.895274e+08,7.858333e+08
11,Random Forest_Tuned,3,6.891336e+08,7.837802e+08,6.891336e+08,7.837802e+08

### LSTM

In [103]:
LSTM_CELL_SIZE= 10
BATCH_SIZE = 100
EPOCHS = 5
DROPOUT_RATE=0.001

In [104]:
metric_lstm_sh = pd.DataFrame()
future_pred_window=1
for l in range(3,15):
    segmenter = SegmentXYForecast(l, step=1, y_func=last,forecast=future_pred_window)
    X_train_rolled, y_train_rolled,_=segmenter.fit_transform([X_train_scaled],[y_train_scaled.flatten()])
    X_test_rolled, y_test_rolled,_=segmenter.fit_transform([X_test_scaled],[y_test_scaled.flatten()])
        #Flattening the train
    shape = X_train_rolled.shape
    X_train_flattened = X_train_rolled.reshape(shape[0],shape[1]*shape[2])
    X_train_flattened.shape
        #Flattening the test
    shape = X_test_rolled.shape
    X_test_flattened = X_test_rolled.reshape(shape[0],shape[1]*shape[2])
    X_test_flattened.shape
    # Building the LSTM model here!
    model_lstm = Sequential()
    model_lstm.add(LSTM(units=LSTM_CELL_SIZE,activation = 'relu',input_shape=(l,4)))
    model_lstm.add(Dense (5, activation = 'relu'))
    model_lstm.add(Dropout(DROPOUT_RATE))
    model_lstm.add(Dense (1))
    model_lstm.compile(loss='mean_squared_error', optimizer=Adam(learning_rate = 0.02),metrics=["accuracy"])
    history = model_lstm.fit(X_train_rolled, y_train_rolled,validation_data=(X_test_rolled, y_test_rolled), epochs=EPOCHS,batch_size=BATCH_SIZE,verbose =1)
    pred_train=model_lstm.predict(X_train_rolled)
    pred_test=model_lstm.predict(X_test_rolled)
    mse_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mse_test=metrics.mean_squared_error(y_test[l:],pred_test)
    mae_train=metrics.mean_squared_error(y_train[l:],pred_train)
    mae_test=metrics.mean_squared_error(y_test[l:],pred_test)
    metric_lstm={'Model':['LSTM'],
            "Time Window" : l,
            'MSE Train':mse_train,
            'MAE Train':mae_train,
            'MSE Test':mse_test,
            'MAE Test':mae_test}
    metric_lstm=pd.DataFrame(metric_lstm)
    metric_lstm_sh = pd.concat([metric_lstm,metric_lstm_sh],ignore_index=True)
    metric_lstm_sh

Epoch 1/5
15/15 [==============================] - 4s 53ms/step - loss: 0.0777 - accuracy: 0.0021 - val_loss: 0.0763 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0639 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0729 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0639 - accuracy: 0.0021 - val_loss: 0.0736 - val_accuracy: 0.0000e+00
45/45 [==============================] - 1s 2ms/step
12/12 [==============================] - 0s 4ms/step
Epoch 1/5
15/15 [==============================] - 3s 42ms/step - loss: 0.0931 - accuracy: 0.0021 - val_loss: 0.0803 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0652 - accuracy: 0.0021 - val_loss: 0.0734 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0636 - accuracy: 0.0021 - val_loss: 0.0740 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0637 - accuracy: 0.0021 - val_loss: 0.0729 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0641 - accuracy: 0.0021 - val_loss: 0.0761 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
12/12 [==============================] - 0s 4ms/step
Epoch 1/5
15/15 [==============================] - 3s 44ms/step - loss: 0.1048 - accuracy: 0.0021 - val_loss: 0.0758 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0643 - accuracy: 0.0021 - val_loss: 0.0741 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0646 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 9ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0739 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
12/12 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 3s 43ms/step - loss: 0.1430 - accuracy: 0.0021 - val_loss: 0.0735 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0638 - accuracy: 0.0021 - val_loss: 0.0757 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 15ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0741 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0631 - accuracy: 0.0021 - val_loss: 0.0734 - val_accuracy: 0.0000e+00
45/45 [==============================] - 1s 3ms/step
12/12 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 3s 41ms/step - loss: 0.0761 - accuracy: 0.0021 - val_loss: 0.0734 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0639 - accuracy: 0.0021 - val_loss: 0.0733 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 11ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0730 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 10ms/step - loss: 0.0635 - accuracy: 0.0021 - val_loss: 0.0731 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0635 - accuracy: 0.0021 - val_loss: 0.0741 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
12/12 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 3s 43ms/step - loss: 0.0781 - accuracy: 0.0021 - val_loss: 0.0744 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0639 - accuracy: 0.0021 - val_loss: 0.0741 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0643 - accuracy: 0.0021 - val_loss: 0.0730 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0630 - accuracy: 0.0021 - val_loss: 0.0739 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0632 - accuracy: 0.0021 - val_loss: 0.0737 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
12/12 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 3s 42ms/step - loss: 0.1273 - accuracy: 0.0021 - val_loss: 0.0763 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0650 - accuracy: 0.0021 - val_loss: 0.0739 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0731 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0629 - accuracy: 0.0021 - val_loss: 0.0728 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0631 - accuracy: 0.0021 - val_loss: 0.0730 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
11/11 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 3s 42ms/step - loss: 0.0977 - accuracy: 0.0021 - val_loss: 0.0746 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0654 - accuracy: 0.0021 - val_loss: 0.0742 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0640 - accuracy: 0.0021 - val_loss: 0.0734 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0737 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 12ms/step - loss: 0.0632 - accuracy: 0.0021 - val_loss: 0.0728 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 3ms/step
11/11 [==============================] - 0s 4ms/step
Epoch 1/5
15/15 [==============================] - 3s 42ms/step - loss: 0.0650 - accuracy: 0.0021 - val_loss: 0.0746 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0636 - accuracy: 0.0021 - val_loss: 0.0737 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0637 - accuracy: 0.0021 - val_loss: 0.0724 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0647 - accuracy: 0.0021 - val_loss: 0.0722 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0629 - accuracy: 0.0021 - val_loss: 0.0723 - val_accuracy: 0.0000e+00
45/45 [==============================] - 1s 4ms/step
11/11 [==============================] - 0s 5ms/step
Epoch 1/5
15/15 [==============================] - 3s 43ms/step - loss: 0.0713 - accuracy: 0.0021 - val_loss: 0.0730 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 15ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0724 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0630 - accuracy: 0.0021 - val_loss: 0.0728 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0635 - accuracy: 0.0021 - val_loss: 0.0722 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0634 - accuracy: 0.0021 - val_loss: 0.0732 - val_accuracy: 0.0000e+00

45/45 [==============================] - 0s 4ms/step
11/11 [==============================] - 0s 4ms/step
Epoch 1/5
15/15 [==============================] - 3s 46ms/step - loss: 0.0760 - accuracy: 0.0021 - val_loss: 0.0730 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 14ms/step - loss: 0.0637 - accuracy: 0.0021 - val_loss: 0.0725 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 15ms/step - loss: 0.0632 - accuracy: 0.0021 - val_loss: 0.0731 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0635 - accuracy: 0.0021 - val_loss: 0.0726 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 13ms/step - loss: 0.0631 - accuracy: 0.0021 - val_loss: 0.0726 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 4ms/step
11/11 [==============================] - 0s 3ms/step
Epoch 1/5
15/15 [==============================] - 4s 65ms/step - loss: 0.0725 - accuracy: 0.0021 - val_loss: 0.0728 - val_accuracy: 0.0000e+00
Epoch 2/5
15/15 [==============================] - 0s 20ms/step - loss: 0.0636 - accuracy: 0.0021 - val_loss: 0.0729 - val_accuracy: 0.0000e+00
Epoch 3/5
15/15 [==============================] - 0s 19ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0725 - val_accuracy: 0.0000e+00
Epoch 4/5
15/15 [==============================] - 0s 19ms/step - loss: 0.0633 - accuracy: 0.0021 - val_loss: 0.0726 - val_accuracy: 0.0000e+00
Epoch 5/5
15/15 [==============================] - 0s 18ms/step - loss: 0.0648 - accuracy: 0.0021 - val_loss: 0.0725 - val_accuracy: 0.0000e+00
45/45 [==============================] - 0s 4ms/step
11/11 [==============================] - 0s 3ms/step

In [105]:
metric_lstm_sh

   Model  Time Window     MSE Train     MAE Train      MSE Test      MAE Test
0   LSTM           14  6.832807e+08  6.832807e+08  7.747560e+08  7.747560e+08
1   LSTM           13  6.843561e+08  6.843561e+08  7.753492e+08  7.753492e+08
2   LSTM           12  6.846518e+08  6.846518e+08  7.767560e+08  7.767560e+08
3   LSTM           11  6.856875e+08  6.856875e+08  7.747423e+08  7.747423e+08
4   LSTM           10  6.868585e+08  6.868585e+08  7.817959e+08  7.817959e+08
5   LSTM            9  6.864186e+08  6.864186e+08  7.831648e+08  7.831648e+08
6   LSTM            8  6.865303e+08  6.865303e+08  7.875230e+08  7.875230e+08
7   LSTM            7  6.881446e+08  6.881446e+08  7.853989e+08  7.853989e+08
8   LSTM            6  6.877337e+08  6.877337e+08  7.895067e+08  7.895067e+08
9   LSTM            5  6.899755e+08  6.899755e+08  7.876864e+08  7.876864e+08
10  LSTM            4  6.895291e+08  6.895291e+08  7.858350e+08  7.858350e+08
11  LSTM            3  6.891343e+08  6.891343e+08  7.837807e+08  7.837807e+08